# Generated by Django 4.2.1 on 2023-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('length', models.IntegerField()),
                ('elevation_gain', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('permit', models.CharField(max_length=20)),
                ('fees', models.CharField(max_length=155)),
            ],
        ),
    ]
