# Generated by Django 4.2.1 on 2023-05-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='elevation_gain',
            new_name='elevationGain',
        ),
    ]
