# Generated by Django 4.2.1 on 2023-05-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathsapi', '0002_rename_elevation_gain_trail_elevationgain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=200)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pathsapi.trail')),
            ],
        ),
    ]
