# Generated by Django 4.2.1 on 2023-05-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathsapi', '0003_campingsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wantlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pathsapi.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('favorite_hike', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=155)),
                ('area', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=155)),
                ('rating', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pathsapi.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completedlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pathsapi.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
