# Generated by Django 4.2.1 on 2023-05-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathsapi', '0004_wantlist_userprofile_review_completedlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
