# Generated by Django 4.2.1 on 2023-05-17 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathsapi', '0007_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campingsite',
            name='trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pathsapi.trail'),
        ),
        migrations.AlterField(
            model_name='completedlist',
            name='trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pathsapi.trail'),
        ),
        migrations.AlterField(
            model_name='completedlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pathsapi.trail'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wantlist',
            name='trail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pathsapi.trail'),
        ),
        migrations.AlterField(
            model_name='wantlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=155)),
                ('date', models.DateField()),
                ('receiver', models.ManyToManyField(related_name='userreceiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(related_name='usersender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
