# Generated by Django 4.2.1 on 2023-05-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathsapi', '0009_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trail',
            name='lon',
            field=models.FloatField(),
        ),
    ]
